controllers:
    resource: ../../src/Controller/
    type: annotation

api_controller:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
